<?php
/* Pgvietnam configs */
return [
    'version' => '1.0.0',
	'status_order'=>[
        1=>'Đang chờ',
        2=>'Đã xác nhận',
        3=>'Đã giao hàng',
        4=>'Đã hủy bỏ',
    ],
    'status_category_network'=>[
        1=>'Active',
        2=>'Inactive',
    ],
    'status_profile'=>[
        1=>'Active',
        2=>'Inactive',
    ],
    'giosinh'=>[
        0=>'Tý (23-01h)',
        1=>'Sửu (1h-3h)',
        2=>'Dần (3h-5h)',
        3=>'Mão (5h-7h)',
        4=>'Thìn (7h-9h)',
        5=>'Tỵ (9h-11h)',
        6=>'Ngọ (11h-13h)',
        7=>'Mùi (13h-15h)',
        9=>'Thân (15h-17h)',
        10=>'Dậu (17h-19h)',
        11=>'Tuất (19h-21h)',
        12=>'Hợi (21h-23h)'

    ],
    'gioitinh'=>[
        1=>'Nam',
        0=>'Nữ'
    ],
    'modules'   => [
        'sim_fate'=>'Sim Hợp Mệnh',
        'sim_age'=>'Sim Hợp Tuổi',
        'orders'=>'Quản lý đơn hàng',
        'genres'=>'thể loại SIM',
        'price_range'=>'Giá SIM',
        'role'                  => 'phân quyền',
        'log'                   => 'log hệ thống',
        'options'               => 'cài đặt',
        'user'                  => 'thành viên',
        'promotion'             => 'mã khuyến mãi',
        'group_service'         => 'group service',
        'page'                  => 'Page',
        'setting'               => 'Setting',
        'category'              => 'Category',
        'tags'                  => 'Tags',
        'news'                  => 'News',
        'group_product'         => 'group product',
        'profile_custom'        => 'profile custom',
        'profile_key'           => 'profile key',
        'order'                 => 'order',
        'product'               => 'product',
        'service'               => 'service',
        'profile_service'       => 'profile service',
        'gallery'               => 'gallery',
        'customer'              => 'customer',
        'transaction'           => 'transaction',
        'transaction_history'   => 'transaction_history',
        'profile'                 => 'Tip',
        'status_plus'                 => 'status_plus',
        'keywords'                 => 'Từ khóa tip',
    ],
    'actions'   => [
        'store'         => 'Thêm',
        'update'        => 'Cập nhật',
        'destroy'       => 'Xóa',
        'trash'       => 'Xóa tạm',
        'removeAll'     => 'Xóa tất cả',
        'approved'      => 'Phê duyệt',
        'not_approved'  => 'Không phê duyệt',
        'reply'         => 'Phản hồi',
        'send'          => 'Gửi tin nhắn',
        'changeList'    => 'Thay đổi danh sách',
        'status_plus'                 => 'Bù Tip',
    ],
    'valid_files' => ['csv', 'txt', 'xls', 'xlsx'],
    'user_type' => [
        'admin'         => 'Admin',
        'customer'      => 'Khách hàng',
        'expert'        => 'Chuyên gia',
    ],
    'message_type'  => [
        'tip'               => 'Gửi tip',
        'expired'           => 'Nhắc gia hạn',
        'promotion'         => 'Khuyến mãi',
        'notify'            => 'Thông báo',
        'facebook'          => 'Đăng Facebook cá nhân',
    ],
];
